FROM golang:1.22.3-alpine3.18 as build
COPY go.* .
RUN go mod download
COPY clone clone
RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-w -s" -o /service ./clone/

FROM gcr.io/distroless/static-debian12
COPY --from=build /service /service
COPY clone/static clone/static
ENTRYPOINT [ "/service" ]